### ISSUE TITLE
CloneVM_Task throws an error

### ISSUE THREAD

**Issue by anikushkin** [vadimcomanescu/vmwarephp#11]
CloneVM_Task throws an error : 

```
PHP Fatal error:  Uncaught exception 'Vmwarephp\Exception\Soap' with message 'ServerFaultCode: . InvalidProperty: InvalidProperty Object
(
    [name] => _
)
' in /root/vmwarephp/library/Vmwarephp/Service.php:77
Stack trace:
#0 /root/vmwarephp/library/Vmwarephp/Service.php(24): Vmwarephp\Service->makeSoapCall('RetrievePropert...', Array)
#1 /root/vmwarephp/library/Vmwarephp/ManagedObject.php(42): Vmwarephp\Service->__call('RetrievePropert...', Array)
#2 /root/vmwarephp/library/Vmwarephp/ManagedObject.php(42): Vmwarephp\Service->RetrieveProperties(Object(Vmwarephp\Extensions\PropertyCollector), Array)
#3 /root/vmwarephp/library/Vmwarephp/Extensions/PropertyCollector.php(28): Vmwarephp\ManagedObject->__call('RetrievePropert...', Array)
#4 /root/vmwarephp/library/Vmwarephp/Extensions/PropertyCollector.php(28): Vmwarephp\Extensions\PropertyCollector->RetrieveProperties(Array)
#5 /root/vmwarephp/library/Vmwarephp/Extensions/PropertyCollector.php(23): Vmwarephp\Extensions\PropertyCollector->getPropertiesUsingSpec(Object(PropertyFilte in /root/vmwarephp/library/Vmwarephp/Service.php on line 77
```

Not sure if it's a bug, may be it's something with my code. Please point me where I'm wrong. vmwarephp source code is latest from github.

Here is my code : 

``` php
$vhost = new \Vmwarephp\Vhost('*****','*****','*****');

$vm = $vhost->findManagedObjectByName("VirtualMachine", "test1", array());
echo "vms is : $vm->name\n";

$cfs = new VirtualMachineCloneSpec();
$cfs->powerOn=FALSE;
$cfs->template=FALSE;
$cfs->snapshot=$vm->snapshot->currentSnapshot;
$cfs->location =new VirtualMachineRelocateSpec();
$cfs->location->diskMoveType='createNewChildDiskBacking';

$ret = $vm->CloneVM_Task(array('folder' => $vm->parent, 'name' => $vm->name .'-clone', 'spec' => $cfs));
```

I added some debug in /root/vmwarephp/library/Vmwarephp/Service.php, but can't find where to digg (following is the output of my script): 

```
vms is : test1
error is - RetrievePropertiesArray
(
    [_this] => ManagedObjectReference Object
        (
            [_] => ha-property-collector
            [type] => PropertyCollector
        )

    [specSet] => PropertyFilterSpec Object
        (
            [propSet] => Array
                (
                    [0] => PropertySpec Object
                        (
                            [type] => Folder
                            [all] => 
                            [pathSet] => Array
                                (
                                    [0] => _
                                )

                        )

                )

            [objectSet] => Array
                (
                    [0] => ObjectSpec Object
                        (
                            [obj] => ManagedObjectReference Object
                                (
                                    [_] => ha-folder-vm
                                    [type] => Folder
                                )

                            [skip] => 
                            [selectSet] => 
                        )

                )

            [reportMissingObjectsInResults] => 
        )

    [options] => Array
        (
        )

)
<here comes the error message I pasted in first block>
```

**Comment by rajukumargupta** [comment]
this error come because your user dnot have permission to clone vm task.
