### ISSUE TITLE
InvalidRequest error with vSphere 4.1.0

### ISSUE THREAD

**Issue by samcrawford** [vadimcomanescu/vmwarephp#16]
Hello,

I've been using vmwarephp very successfully with vSphere 5.5 - thanks for the great library!

However, I've got to use it with vSphere 4.1.0 now, which is supported according to the docs. However, I'm just getting a very anonymous error when trying to use it:

```
PHP Fatal error:  Uncaught exception 'Vmwarephp\Exception\Soap' with message 'ServerFaultCode: type. InvalidRequest: InvalidRequest Object
(
)
' in /root/vmw/vmwarephp/library/Vmwarephp/Service.php:74
Stack trace:
#0 /root/vmw/vmwarephp/library/Vmwarephp/Service.php(57): Vmwarephp\Service->makeSoapCall('RetrieveService...', Array)
#1 /root/vmw/vmwarephp/library/Vmwarephp/Service.php(82): Vmwarephp\Service->getServiceContent()
#2 /root/vmw/vmwarephp/library/Vmwarephp/Service.php(21): Vmwarephp\Service->getQueriedProperty('getSessionManag...', Array)
#3 /root/vmw/vmwarephp/library/Vmwarephp/Service.php(50): Vmwarephp\Service->__call('getSessionManag...', Array)
#4 /root/vmw/vmwarephp/library/Vmwarephp/Service.php(50): Vmwarephp\Service->getSessionManager()
#5 /root/vmw/vmwarephp/library/Vmwarephp/Factory/Service.php(13): Vmwarephp\Service->connect()
#6 /root/vmw/vmwarephp/library/Vmwarephp/Vhost.php(45): Vmwarephp\Factory\Service::makeConnected(Object(Vmwarephp\Vhost))
#7 /root/vmw/vmwarephp/library/Vmwarephp/Vhost.php(31): Vmwa in /root/vmw/vmwarephp/library/Vmwarephp/Service.php on line 74
```

Here's our VMWare version:

```
VMware vSphere Web Access Version 4.1.0 Build 426686
VMware vCenter Server Version 4.1.0 Build 491557
```

Any suggestions? Is there something wrong with our VMWare setup that is disallowing API access?

Thanks in advance!

**Comment by geoff-maddock** [comment]
Interesting, I'm having the same issue, except that I'm connecting to vSphere 5.5. 

Did you figure out the issue, sam?
